workflows:
  ios-native-quick-start:
    name: iOS Native
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Amwal CodeMagic
    environment:
      ios_signing:
        provisioning_profiles:
          - Amwal Native
        certificates:
          - Code Magic Apple Dis
      vars:
        XCODE_WORKSPACE: "AnwalPaySDKNativeiOSExample.xcworkspace"
        XCODE_SCHEME: "AnwalPaySDKNativeiOSExample"
        APP_STORE_APPLE_ID: 6744919252
        XCODE_VERBOSE: true
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          pod install --repo-update

      - name: Increment build number
        script: |
          cd $CM_BUILD_DIR
          echo "Current PROJECT_BUILD_NUMBER is $PROJECT_BUILD_NUMBER"
          agvtool new-version -all "$PROJECT_BUILD_NUMBER"

      - name: Debug code signing setup
        script: |
          echo "Available provisioning profiles:"
          security find-identity -v -p codesigning
          echo "Available certificates:"
          security find-certificate -a

      - name: Archive app with xcodebuild (Verbose)
        script: |
          xcodebuild -workspace "$XCODE_WORKSPACE" \
                     -scheme "$XCODE_SCHEME" \
                     -configuration Release \
                     -destination "generic/platform=iOS" \
                     -archivePath $CM_BUILD_DIR/AnwalPaySDKNativeiOSExample.xcarchive \
                     archive \
                     CODE_SIGN_IDENTITY="Apple Distribution" \
                     CODE_SIGN_STYLE=Manual \
                     DEVELOPMENT_TEAM=U7372H8TUQ \
                     -verbose

      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
                     -archivePath $CM_BUILD_DIR/AnwalPaySDKNativeiOSExample.xcarchive \
                     -exportOptionsPlist exportOptions.plist \
                     -exportPath $CM_BUILD_DIR/ipa
    artifacts:
    - build/ios/ipa/*.ipa
    - /tmp/xcodebuild_logs/*.log
    - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
    - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - amr.saied@amwal-pay.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Testers
        submit_to_app_store: false
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true