workflows:
  ios-native-quick-start:
    name: iOS Native
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Amwal CodeMagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.anwalpay.sdk.example
        provisioning_profiles:
          - Amwal Native
        certificates:
          - Code Magic Apple Dis
      vars:
        XCODE_WORKSPACE: "AnwalPaySDKNativeiOSExample.xcworkspace"
        XCODE_SCHEME: "AnwalPaySDKNativeiOSExample"
        APP_STORE_APPLE_ID: 6744919252
      xcode: 16.3
      cocoapods: default
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          pod install
      - name: Increment build number
        script: |
          cd $CM_BUILD_DIR
          echo "Current PROJECT_BUILD_NUMBER is $PROJECT_BUILD_NUMBER"
          agvtool new-version -all "$PROJECT_BUILD_NUMBER"
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Build IPA for App Store distribution
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --export-options-plist=AnwalPaySDKNativeiOSExample/export_options.plist \
            --verbose \
            --clean
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - amr.saied@amwal-pay.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Testers
        submit_to_app_store: false
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true